# Generated by Django 5.2 on 2025-05-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='場所名')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '場所',
                'verbose_name_plural': '場所',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='種名')),
                ('genus', models.CharField(blank=True, max_length=100, null=True, verbose_name='属名')),
                ('family', models.CharField(blank=True, max_length=100, null=True, verbose_name='科名')),
            ],
            options={
                'verbose_name': '種',
                'verbose_name_plural': '種',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='採取日')),
                ('count', models.IntegerField(default=1, verbose_name='個体数')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='体長')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='湿重量')),
                ('water_temperature', models.FloatField(blank=True, null=True, verbose_name='水温')),
                ('flow_rate', models.FloatField(blank=True, null=True, verbose_name='流速')),
                ('water_depth', models.FloatField(blank=True, null=True, verbose_name='水深')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.location', verbose_name='採取場所')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.species', verbose_name='種')),
            ],
            options={
                'verbose_name': '記録',
                'verbose_name_plural': '記録',
            },
        ),
    ]
