# Generated by Django 5.2 on 2025-05-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='調査日')),
                ('note', models.TextField(blank=True, null=True, verbose_name='調査メモ')),
            ],
            options={
                'verbose_name': '調査',
                'verbose_name_plural': '調査',
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='科'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='属'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=200, verbose_name='種'),
        ),
        migrations.AddField(
            model_name='record',
            name='survey',
            field=models.ForeignKey(default=2828642674928, on_delete=django.db.models.deletion.CASCADE, to='records.survey', verbose_name='調査日'),
            preserve_default=False,
        ),
    ]
