# Generated by Django 5.2 on 2025-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_survey_remove_record_date_alter_species_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='学名'),
        ),
    ]
