# Generated by Django 5.2 on 2025-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_species_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='record',
            name='flow_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='流速(m/s)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='体長(mm)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='water_depth',
            field=models.FloatField(blank=True, null=True, verbose_name='水深(m)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='water_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='水温(℃)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='湿重量(g)'),
        ),
    ]
